# Generated by Django 5.2.4 on 2025-07-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0004_remove_cheque_other_responsible_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed')], max_length=50),
        ),
    ]
